# Configuration for cargo-audit
# This file defines security advisories to ignore, mirroring the exceptions in deny.toml

[advisories]
# List of advisory IDs to ignore (extracted from deny.toml)
ignore = [
    "RUSTSEC-2023-0071", # rsa
    "RUSTSEC-2024-0388", # unmaintained derivative
    "RUSTSEC-2024-0384", # unmaintained instant
    "RUSTSEC-2024-0416", # unmaintained atk-sys
    "RUSTSEC-2024-0418", # unmaintained gdk-sys
    "RUSTSEC-2024-0420", # unmaintained gtk-sys
    "RUSTSEC-2024-0436", # unmaintained paste
]