[workspace]
members = ["crate/cli", "crate/gui"]

# Do that if you don't want to enable `dev` feature by default due to the `dev-dependencies` of the cli.
# For more details, read: https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
# note: resolver defaults to 2 in 2021 edition crate, but defaults to 1 in virtual workspace
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.83.0"
authors = [
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com>",
]
license = "BUSL-1.1" # "Business Source License 1.1"
license-file = "LICENSE"
repository = "https://github.com/Cosmian/cli"
keywords = ["cosmian_cli", "kms", "findex", "findex-server", "cosmian"]
categories = ["security"]

[profile.release]
lto = true
strip = true

[profile.dev]
strip = "debuginfo"
incremental = false

# proc-macros and build-scripts
[profile.dev.build-override]
strip = "debuginfo"
incremental = false

# external dependencies
[profile.dev.package."*"]
opt-level = 0

[workspace.dependencies]
base64 = "0.22"
clap = { version = "4.5.28", default-features = false }
cosmian_crypto_core = { version = "10.0", default-features = false }
cosmian_findex = { git = "https://github.com/Cosmian/findex", features = [
  "redis-mem",
], rev = "98fcb6e97054e1bb9dddd7a0d620e27438cb91b7" }
### KMS
cosmian_kms_cli = { git = "https://www.github.com/Cosmian/kms", branch = "feat/add_digest_and_mac_kmip_operations" }
### findex-server
# cosmian_findex_client = { path = "../crate/client" }
# cosmian_findex_structs = { path = "../crate/structs" }
# test_findex_server = { path = "../crate/test_server" }
cosmian_findex_client = { git = "https://www.github.com/Cosmian/findex-server", branch = "merge_cli" }
cosmian_findex_structs = { git = "https://www.github.com/Cosmian/findex-server", branch = "merge_cli" }
test_findex_server = { git = "https://www.github.com/Cosmian/findex-server", branch = "merge_cli" }
### http_client_server
cosmian_config_utils = { git = "https://www.github.com/Cosmian/http_client_server", tag = "0.1.0" }
cosmian_http_client = { git = "https://www.github.com/Cosmian/http_client_server", tag = "0.1.0" }
cosmian_logger = { git = "https://www.github.com/Cosmian/http_client_server", tag = "0.1.0" }
hex = { version = "0.4", default-features = false }
openssl = { version = "0.10", default-features = false }
serde = "1.0"
thiserror = "2.0"
tokio = { version = "1.43", default-features = false }
tracing = "0.1"
url = "2.5"
uuid = "1.12"
x509-parser = "0.17"
