---
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 5

  findex-server:
    depends_on:
      - redis
    container_name: findex-server
    image: ghcr.io/cosmian/findex-server:develop
    ports:
      - 6669:6668
    environment:
      RUST_LOG: cosmian_findex_server=trace
      FINDEX_SERVER_DATABASE_TYPE: redis
      FINDEX_SERVER_DATABASE_URL: redis://redis:6379

  kms:
    container_name: kms
    # image: ghcr.io/cosmian/kms:4.22.1
    image: ghcr.io/cosmian/kms:develop
    ports:
      - 19998:9998
