---
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kms
      - POSTGRES_DB=kms
      - POSTGRES_PASSWORD=kms
      - PGDATA=/tmp/postgres2
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=kms
      - MARIADB_USER=kms
      - MARIADB_PASSWORD=kms
      - MYSQL_DATABASE=kms
      - MYSQL_ROOT_PASSWORD=kms
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - '6379'
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 5
