---
services:
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: 1234
      ENABLE_ARCHIVELOG: true
      ENABLE_FORCE_LOGGING: true
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./keystore:/opt/oracle/keystore
