---
services:
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: 1234
      ENABLE_ARCHIVELOG: true
      ENABLE_FORCE_LOGGING: true
      COSMIAN_PKCS11_LOGGING_LEVEL: trace
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:5.7.0
    ports:
      - 9998:9998
    environment:
      RUST_LOG: cosmian_kms_server=trace
    volumes:
      - ./cosmian-kms:/cosmian-kms
