# Configuration for cargo-audit
# This file defines security advisories to ignore, mirroring the exceptions in deny.toml

[advisories]
# List of advisory IDs to ignore (extracted from deny.toml)
ignore = [
    "RUSTSEC-2023-0071", # rsa
    "RUSTSEC-2025-0052", # async-std has been discontinued
]
