# Use rust-lld (LLVM's lld-link) instead of MSVC link.exe to avoid
# LNK1189: library limit of 65535 objects exceeded on large workspaces.
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld.exe"
