# On Windows, the linker may exceed its number of allowed symbols
# This is likely going to require nightly
# see https://github.com/rust-lang/rust/issues/53014#issuecomment-646149774
[target.aarch64-pc-windows-msvc]
rustflags = "-Zshare-generics=off"
[target.x86_64-pc-windows-msvc]
rustflags = "-Zshare-generics=off"
