---
services:
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:5.9.0
    ports:
      - 9998:9998
    environment:
      RUST_LOG: cosmian_kms_server=trace
    volumes:
      - ./cosmian-kms:/cosmian-kms
