[package]
name = "cosmian_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI used to manage the Cosmian KMS."

[[bin]]
name = "cosmian"
path = "src/main.rs"
test = false

[lib]
# doc test linking as a separate binary is extremely slow
# and is not needed for internal lib
doctest = false

[features]
fips = ["cosmian_kms_cli/fips"]

[dependencies]
clap = { workspace = true, features = [
  "help",
  "env",
  "std",
  "usage",
  "error-context",
  "derive",
  "cargo",
] }
cosmian_kms_cli = { workspace = true }
cosmian_findex_cli = { workspace = true }
cosmian_config_utils = { workspace = true }
cosmian_logger = { workspace = true }
csv = "1.3.1"
hex = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
actix-rt = "2.10"
actix-server = { version = "2.5", default-features = false }
assert_cmd = "2.0"
const-oid = { version = "0.9", features = ["db"] }
lazy_static = "1.4"
openssl = { workspace = true }
predicates = "3.1"
regex = { version = "1.11", default-features = false }
tempfile = "3.14"
x509-parser = { workspace = true, features = ["verify"] }

# ------------------------------------------------------------------------------
# START DEBIAN PACKAGING
[package.metadata.deb]
maintainer = "Emmanuel Coste <emmanuel.coste@cosmian.com>"
copyright = "2024, Cosmian Tech SAS <tech@cosmian.com>"
license-file = ["../../LICENSE", "0"]
changelog = "../../CHANGELOG.md"
section = "security"
priority = "optional"
assets = [
  [
    "target/release/cosmian",
    "usr/sbin/",
    "555",
  ],
  [
    "target/release/cosmian_gui",
    "usr/sbin/",
    "555",
  ],
]

[package.metadata.deb.variants.fips]
features = ["fips"]

# END DEBIAN PACKAGING
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# START RPM PACKAGING
[package.metadata.generate-rpm]
license = "BUSL-1.1"
assets = [
  { source = "target/release/cosmian", dest = "/usr/sbin/cosmian", mode = "555" },
  { source = "target/release/cosmian_gui", dest = "/usr/sbin/cosmian_gui", mode = "555" },
]
auto-req = "no" # do not try to discover .so dependencies
require-sh = true

# END RPM PACKAGING
# ------------------------------------------------------------------------------
