---
name: Build all

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  rhel9:
    name: RHEL9
    uses: ./.github/workflows/build_rhel9.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: rhel9
      target: x86_64-unknown-linux-gnu
      debug_or_release: ${{ inputs.debug_or_release }}
      skip_services_tests: --skip hsm

  generic:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: ubuntu-22.04
            archive-name: ubuntu_22_04
            target: x86_64-unknown-linux-gnu
            prerequisites: |
              sudo apt-get update
              sudo apt-get install -qq librust-atk-sys-dev librust-gdk-sys-dev pkg-config jq
            skip_services_tests: --skip hsm
            docker_compose: true

          - distribution: ubuntu-24.04
            archive-name: ubuntu_24_04
            target: x86_64-unknown-linux-gnu
            prerequisites: |
              sudo apt-get update
              sudo apt-get install -qq libgtk-3-dev libglib2.0-dev pkg-config jq
            skip_services_tests: --skip hsm
            docker_compose: true

          - distribution: macos-13
            archive-name: macos_intel
            target: x86_64-apple-darwin
            skip_services_tests: --skip findex_server --skip hsm
            docker_compose: false

          - distribution: macos-14
            archive-name: macos_arm
            target: aarch64-apple-darwin
            skip_services_tests: --skip findex_server --skip hsm
            docker_compose: false

    name: ${{ matrix.distribution }}
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ${{ matrix.distribution }}
      archive-name: ${{ matrix.archive-name }}
      target: ${{ matrix.target }}
      debug_or_release: ${{ inputs.debug_or_release }}
      prerequisites: ${{ matrix.prerequisites }}
      skip_services_tests: ${{ matrix.skip_services_tests }}
      docker_compose: ${{ matrix.docker_compose }}

  windows-2022:
    if: inputs.debug_or_release == 'release'
    uses: ./.github/workflows/build_windows.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: windows
      debug_or_release: ${{ inputs.debug_or_release }}

  cleanup:
    needs:
      - rhel9
      - generic
      - windows-2022
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@develop
    secrets: inherit
