---
name: CLI cargo build

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      distribution:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      target:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string
      skip_services_tests:
        required: false
        type: string
      prerequisites:
        required: false
        type: string
      docker_compose:
        required: false
        type: boolean
        default: false

env:
  OPENSSL_DIR: /usr/local/openssl

jobs:
  cli-build:
    name: ${{ inputs.archive-name }}
    runs-on: ${{ inputs.distribution }}
    steps:
      - name: Display cpuinfo
        if: contains(runner.os, 'Linux')
        run: cat /proc/cpuinfo

      - run: |
          sudo mkdir -p ${{ env.OPENSSL_DIR }}/ssl
          sudo mkdir -p ${{ env.OPENSSL_DIR }}/lib64/ossl-modules
          sudo chown -R $USER ${{ env.OPENSSL_DIR }}

      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - name: Run docker containers
        if: ${{ inputs.docker_compose }}
        run: |
          docker compose -h
          docker compose up -d

      - name: Prerequisites
        if: ${{ inputs.prerequisites }}
        run: |
          set -ex
          ${{ inputs.prerequisites }}

      - name: Local OpenSSL FIPS Install
        run: |
          sudo mkdir -p ${{ env.OPENSSL_DIR }}
          sudo chown -R $USER ${{ env.OPENSSL_DIR }}
          bash .github/scripts/get_openssl_binaries.sh
        env:
          OS_NAME: ${{ inputs.archive-name }}

      - name: Build and tests
        env:
          OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
          TEST_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_ID }}
          TEST_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_SECRET }}
          TEST_GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.TEST_GOOGLE_OAUTH_REFRESH_TOKEN }}
          TARGET: ${{ inputs.target }}
          DEBUG_OR_RELEASE: ${{ inputs.debug_or_release }}
          SKIP_SERVICES_TESTS: ${{ inputs.skip_services_tests }}
        run: |
          bash .github/scripts/cargo_build.sh

      - name: Cosmian tests
        if: contains(runner.os, 'Linux')
        run: |
          set -ex
          bash .github/scripts/cosmian_tests.sh

      - name: Remove large files before saving cache
        run: |
          find target/ -type f -size +100M -delete

      - name: Upload CLI for ${{ inputs.distribution }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}
          path: |
            target/${{ inputs.target }}/${{ inputs.debug_or_release }}/cosmian
            target/${{ inputs.target }}/${{ inputs.debug_or_release }}/cosmian_gui
            target/${{ inputs.target }}/${{ inputs.debug_or_release }}/libcosmian_pkcs11.*
            target/${{ inputs.target }}/debian/*.deb
          retention-days: 1
          if-no-files-found: error

  cli-test:
    needs: cli-build
    name: Clean env. ${{ inputs.archive-name }}
    runs-on: ${{ inputs.distribution }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}

      - run: find .
        if: contains(runner.os, 'linux')

      - name: Linux launch cosmian and cosmian_gui
        if: contains(runner.os, 'Linux')
        run: |
          set -ex
          # The current path should be /home/runner/work/cli/cli
          pwd
          find . -type f
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_gui

          ./${{ inputs.debug_or_release }}/cosmian -V
          ./${{ inputs.debug_or_release }}/cosmian_gui -V

      - name: MacOS launch cosmian and cosmian_gui
        if: contains(runner.os, 'macos')
        run: |
          set -ex
          # The current path should be /Users/runner/work/cli/cli
          pwd
          ls -lah
          find . -type f
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_gui

          ./${{ inputs.debug_or_release }}/cosmian -V
          ./${{ inputs.debug_or_release }}/cosmian_gui -V
