---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  cargo-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  cargo-lint:
    uses: ./.github/workflows/clippy.yml
    with:
      toolchain: ${{ inputs.toolchain }}

  build:
    uses: ./.github/workflows/build_all.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      debug_or_release: ${{ inputs.debug_or_release }}

  ##############################################################################
  ### Releases
  ##############################################################################
  release:
    name: release
    needs:
      - cargo-audit
      - cargo-lint
      - build
    runs-on: [self-hosted, not-sgx]
    container:
      image: cosmian/docker_doc_ci
      volumes:
        - /home/cosmian/.ssh/id_rsa:/root/.ssh/id_rsa

    env:
      ARCHIVE_NAMES: rhel9-${{ inputs.debug_or_release }} ubuntu_2*_04-${{ inputs.debug_or_release }} macos_*-${{ inputs.debug_or_release }}

    steps:
      - uses: actions/checkout@v3
      - run: rm -rf windows* ubuntu* macos* rhel9*
      - uses: actions/download-artifact@v4

      - run: find .

      - name: Push to package.cosmian.com
        shell: bash
        run: |
          bash .github/scripts/push_to_package_cosmian.sh "${{ inputs.debug_or_release }}"

      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            rhel9-release/generate-rpm/*.rpm \
            ubuntu_22_04-release/debian/*.deb \
            ubuntu_24_04-release/debian/*.deb

  public_documentation:
    needs:
      - cargo-audit
      - cargo-lint
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy documentation in staging
        if: ${{ github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: staging.yml
          repo: Cosmian/public_documentation
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: prod.yml
          repo: Cosmian/public_documentation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
