---
name: CI in debug

on:
  push:
    tags-ignore:
      - '**'

jobs:
  main:
    uses: ./.github/workflows/main_base.yml
    secrets: inherit
    with:
      toolchain: nightly-2025-03-31
      debug_or_release: debug
