---
name: CI in debug

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/main_base.yml
    secrets: inherit
    with:
      toolchain: nightly-2025-09-15
      debug_or_release: debug
      platforms: linux/amd64
