---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  cargo-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  cargo-lint:
    uses: ./.github/workflows/clippy.yml
    with:
      toolchain: ${{ inputs.toolchain }}

  build:
    uses: ./.github/workflows/build_all.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      debug_or_release: ${{ inputs.debug_or_release }}

  ##############################################################################
  ### Releases
  ##############################################################################
  release:
    name: release
    needs:
      - cargo-audit
      - cargo-lint
      - build
    runs-on: [self-hosted, not-sgx]
    container:
      image: cosmian/docker_doc_ci
      volumes:
        - /home/cosmian/.ssh/id_rsa:/root/.ssh/id_rsa

    env:
      ARCHIVE_NAMES: rhel9-${{ inputs.debug_or_release }} ubuntu_20_04-${{ inputs.debug_or_release }} ubuntu_22_04-${{ inputs.debug_or_release }} ubuntu_24_04-${{
        inputs.debug_or_release }} macos_intel-${{ inputs.debug_or_release }} macos_arm-${{ inputs.debug_or_release }} }}

    steps:
      - run: rm -rf windows* ubuntu* macos* rhel9*
      - uses: actions/download-artifact@v3

      - run: find .

      - name: Creating zip to be attached to release
        run: |
          apt update -y
          apt-get install -y zip
          for archive_name in $ARCHIVE_NAMES; do
            zip -r "$archive_name".zip "$archive_name"
          done
          # Warning, no windows binaries in debug
          if [ "${{ inputs.debug_or_release }}" == "release" ]; then
            zip -r "$archive_name".zip windows-release
          fi

      - name: Push to package.cosmian.com
        shell: bash
        run: |
          set -x
          if [[ "${GITHUB_REF}" =~ 'refs/tags/' ]]; then
            BRANCH="${GITHUB_REF_NAME}"
          else
            BRANCH="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          fi
          DESTINATION_DIR=/mnt/package/cli/$BRANCH
          ssh -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa \
            *.zip \
            cosmian@package.cosmian.com:$DESTINATION_DIR/

          ssh -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR/{rhel9,ubuntu-20.04,ubuntu-22.04,ubuntu-24.04}

          # RedHat 9 package
          scp -o 'StrictHostKeyChecking no' \
            -i /root/.ssh/id_rsa rhel9-${{ inputs.debug_or_release }}/__w/cli/cli/target/x86_64-unknown-linux-gnu/generate-rpm/*.rpm \
            cosmian@package.cosmian.com:$DESTINATION_DIR/rhel9

          # Ubuntu packages
          scp -o 'StrictHostKeyChecking no' \
            -i /root/.ssh/id_rsa ubuntu_20_04-${{ inputs.debug_or_release }}/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb \
            cosmian@package.cosmian.com:$DESTINATION_DIR/ubuntu-20.04
          scp -o 'StrictHostKeyChecking no' \
            -i /root/.ssh/id_rsa ubuntu_22_04-${{ inputs.debug_or_release }}/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb \
            cosmian@package.cosmian.com:$DESTINATION_DIR/ubuntu-22.04
          scp -o 'StrictHostKeyChecking no' \
            -i /root/.ssh/id_rsa ubuntu_24_04-${{ inputs.debug_or_release }}/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb \
            cosmian@package.cosmian.com:$DESTINATION_DIR/ubuntu-24.04

      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            rhel9-release/__w/cli/cli/target/x86_64-unknown-linux-gnu/generate-rpm/*.rpm \
            ubuntu_20_04-release/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb \
            ubuntu_22_04-release/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb \
            ubuntu_24_04-release/home/runner/work/cli/cli/target/x86_64-unknown-linux-gnu/debian/*.deb

  public_documentation:
    needs:
      - release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy documentation in staging
        if: ${{ github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: staging.yml
          repo: Cosmian/public_documentation
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: prod.yml
          repo: Cosmian/public_documentation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
