---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string
      platforms:
        required: true
        type: string

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/clippy.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-deny:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-audit.yml@develop
    name: Security Audit
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-machete:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-machete.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-publish:
    uses: ./.github/workflows/cargo_publish.yml
    secrets:
      token: ${{ secrets.CRATES_IO }}

  forward-proxy:
    uses: ./.github/workflows/forward_proxy.yml
    with:
      toolchain: ${{ inputs.toolchain }}

  build:
    uses: Cosmian/reusable_workflows/.github/workflows/build_all.yml@develop
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      debug_or_release: ${{ inputs.debug_or_release }}

  docker-image:
    name: Build docker image
    if: github.repository == 'Cosmian/cli' && !startsWith(github.ref_name, 'dependabot/')
    uses: Cosmian/reusable_workflows/.github/workflows/build_docker_image.yml@develop
    with:
      prefix: ''
      registry-image: ghcr.io/cosmian/cli
      platforms: ${{ inputs.platforms }}
      fips: false

  ##############################################################################
  ### Releases
  ##############################################################################
  release:
    name: release
    if: github.repository == 'Cosmian/cli' && !startsWith(github.ref_name, 'dependabot/')
    needs:
      - cargo-lint
      - cargo-deny
      - cargo-machete
      - forward-proxy
      - build
    uses: Cosmian/reusable_workflows/.github/workflows/push-artifacts.yml@develop
    with:
      project-name: cli
      destination: cli # /mnt/packages/cli
      debug_or_release: ${{ inputs.debug_or_release }}

  public_documentation:
    if: github.repository == 'Cosmian/cli' && !startsWith(github.ref_name, 'dependabot/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy documentation in staging
        if: ${{ github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: staging.yml
          repo: Cosmian/public_documentation
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: prod.yml
          repo: Cosmian/public_documentation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
